packages: add ns-netmap
NethServer/nethsecurity pull request #324
Opened 2024-02-08 14:15 UTC by gsanchietti

This is a cli-only implementation of netmap.

See [README](https://github.com/NethServer/nethsecurity/blob/netmap/packages/ns-netmap/README.md) for more info on how to use it.

TODO:
- [x] verify the behavior
- [x] implement a pre-commit hook to generate the rules

Card: https://trello.com/c/tavYHA5b/283-nat-rules-source-and-destination-netmap

2024-02-09 08:43 UTC, cotosso commented on packages/ns-netmap/README.md
> +	option src '10.50.50.0/24'
```suggestion
	option dest '10.50.50.0/24'
```

2024-02-09 08:43 UTC, cotosso commented on packages/ns-netmap/README.md
> +	option dest '10.50.50.0/24'
```suggestion
	option src '10.50.50.0/24'
```

2024-02-09 17:21 UTC, filippocarletti requested changes

2024-02-09 17:21 UTC, filippocarletti commented on packages/ns-netmap/README.md
> +This package implements nft netmap rules thar not supported by fw4.
```suggestion
This package implements nft netmap rules not supported by fw4.
```

2024-02-09 17:21 UTC, filippocarletti commented on packages/ns-netmap/README.md
> +- `device_in`: list of coming network interfaces (optional)
```suggestion
- `device_in`: list of incoming network interfaces (optional)
```

2024-02-09 17:21 UTC, filippocarletti commented on packages/ns-netmap/README.md
> +After adding a rule, execute the following to generate the rules:
```suggestion
After adding a rule, execute the following commands to generate the rules:
```

2024-02-09 17:21 UTC, filippocarletti commented on packages/ns-netmap/Makefile
> +	URL:=https://github.com/NethServer/nethsecurity-controller/
Maybe https://github.com/NethServer/nethsecurity

2024-02-12 17:07 UTC, filippocarletti approved these changes

2024-02-13 07:18 UTC, merged