packages: add irqbalance
NethServer/nethsecurity pull request #433
Opened 2024-04-17 11:06 UTC by filippocarletti

2024-04-17 12:30 UTC, gsanchietti requested changes

2024-04-17 12:30 UTC, gsanchietti commented on config/irqbalance.conf
> +CONFIG_PACKAGE_irqbalance=y
Build it as a module:
```suggestion
CONFIG_PACKAGE_irqbalance=m
```

2024-07-24 10:54 UTC, filippocarletti commented
Benchmarks on a 2 cores (4 threads) i5-3320M do NOT show relevant performance gain.
Tested with iperf3 and curl.

2024-07-25 17:31 UTC, filippocarletti commented
Also on i7. Closing.

2024-07-25 17:31 UTC, closed without merging