Add 'sticky' field to API request parameters
NethServer/nethsecurity pull request #582
Opened 2024-06-07 10:11 UTC by stephdl

Add sticky options to store_rule and edit_rule

https://github.com/NethServer/nethsecurity/issues/581

2024-06-10 08:54 UTC, andre8244 approved these changes

2024-06-10 10:35 UTC, Tbaile requested changes

2024-06-10 10:35 UTC, Tbaile commented on packages/ns-api/files/ns.mwan
> +            'sticky': 'String',
Just a little leftover

2024-06-13 07:26 UTC, Tbaile approved these changes

2024-06-17 10:29 UTC, gsanchietti approved these changes

2024-06-17 10:54 UTC, gsanchietti requested changes
python3-nethsec has been bumped to 0.0.59
Please fix the commit style accordingly to conventions: https://dev.nethsecurity.org/development_process/#commit-message-style-guide

2024-06-17 15:47 UTC, gsanchietti approved these changes
I'm going to fix the commit during the squash

2024-06-17 15:48 UTC, merged