Update log rotation size to 1GB
NethServer/nethsecurity pull request #844
Opened 2024-10-11 05:57 UTC by stephdl

This pull request updates the log rotation size in the `ns-storage` package to 1GB. Previously, the size was set to 50MB. The change is made in the `/etc/rsyslog.conf` file, where the log rotation configuration is defined. The new configuration ensures that in-memory logs are rotated when their size exceeds 1GB.

2024-10-11 14:49 UTC, stephdl commented
traffic generator https://gist.github.com/stephdl/43e0f589625d192c467f227a4998d061

2024-10-14 07:22 UTC, gsanchietti reviewed
After reviewing the implementation and considering feedback, we noticed that the current approach of setting the log rotation size to 1GB could create issues, especially on systems with limited RAM, such as machines with only 1GB of memory. For instance, when using tmpfs for storing logs, which typically allocates less than 500MB on such systems, a 1GB log size would not fit.

We propose an alternative solution:

Set the default log rotation size to a dynamic value, such as 10% of the tmpfs size.
Additionally, allow the value to be configurable via UCI, so users with specific requirements can adjust the setting as needed.
This approach ensures better flexibility and scalability across different system configurations.

2024-10-18 08:26 UTC, gsanchietti commented on packages/ns-storage/files/30_ns-storage
> +	option rotate_command '/usr/sbin/rotate-messages'
While this seems a nice idea, we are trying to keep the package in sync with upstream which does not have such support inside the init.d.
I eventually move this to an upstream patch.

2024-10-18 08:26 UTC, gsanchietti commented on packages/ns-storage/files/30_ns-storage
> +fi
I really like the logic of the minimum log_size :+1: 
Still, the current implementation has a big caveats: the `30_ns-storage` uci-default is ignored during package updates and it's not present after install; an uci-default can be used only during an image upgrade.

So this is my proposal:
- keep line 3 unchanged and remove lines from 4 to 6 (see the comment below).
- keep the minimum log_size logic and write it directly to the `/etc/rsyslog.conf` file 
- create a new script named something like `ns-log-size` or similar
- the new script does not really need a config inside UCI, but we can use the `/etc/rsyslog.conf` as "database" (the file is preserved between upgrades); the script could have 2 actions:
  - get: that read the current value
  - set: set a new value

I've asked Copilot for a proof of concept (not really tested):
```bash
#!/bin/bash

CONFIG_FILE="/etc/rsyslog.conf"
LOG_ROTATION_LINE=$(grep -E '^\$outchannel log_rotation' "$CONFIG_FILE")

get_log_rotation_size() {
    echo "$LOG_ROTATION_LINE" | awk -F', ' '{print $2}'
}

set_log_rotation_size() {
    local new_size=$1
    if [[ ! $new_size =~ ^[0-9]+$ ]]; then
        echo "Error: Size must be a positive integer."
        exit 1
    fi
    sed -i -E "s/(\$outchannel log_rotation,\/var\/log\/messages, )[0-9]+(, \/usr\/sbin\/rotate-messages)/\1$new_size\2/" "$CONFIG_FILE"
}

case $1 in
    get)
        get_log_rotation_size
        ;;
    set)
        if [ -z "$2" ]; then
            echo "Error: No size provided for set action."
            exit 1
        fi
        set_log_rotation_size "$2"
        ;;
    *)
        echo "Usage: $0 {get|set <size>}"
        exit 1
        ;;
esac
```

The new script can be called from command line or, in the future, from the UI

2024-10-18 10:07 UTC, gsanchietti requested changes
The new dynamic default should be set also on new installation:
call the new script inside 30_ns-storage

2024-10-18 10:07 UTC, gsanchietti commented on files/usr/sbin/ns-log-size
> +    echo "Current matching line: $LOG_ROTATION_LINE"
Remove debug line.

2024-10-18 10:07 UTC, gsanchietti commented on files/usr/sbin/ns-log-size
> +    echo "Updated matching line: $updated_line"
Remove debug line.

2024-10-18 10:07 UTC, gsanchietti commented on files/usr/sbin/ns-log-size
> +        echo "Failed to update log rotation size."
Exit with 1

2024-10-18 10:07 UTC, gsanchietti commented on files/usr/sbin/ns-log-size
> +        echo "Please restart the rsyslog service to apply the changes."
Let's restart/reload it automatically

2024-10-18 12:08 UTC, gsanchietti requested changes
See previous comment: https://github.com/NethServer/nethsecurity/pull/844#pullrequestreview-2377639901

2024-10-18 12:52 UTC, gsanchietti commented on packages/ns-storage/files/30_ns-storage
>  echo '# Rotate in-memory log if size is bigger than 50MB' >> /etc/rsyslog.conf
Remove the comment because it will not be updated by the ns-log-size script
```suggestion
```

2024-10-18 12:56 UTC, gsanchietti commented on packages/ns-storage/files/30_ns-storage
>  echo '$outchannel log_rotation,/var/log/messages, 52428800, /usr/sbin/rotate-messages' >> /etc/rsyslog.conf
Let's remove it and write the file only once
```suggestion
```

2024-10-18 12:56 UTC, gsanchietti commented on packages/ns-storage/files/30_ns-storage
> +		/usr/sbin/ns-log-size set $log_size
Write directly the config file, not tested:
```suggestion
		echo '$outchannel log_rotation,/var/log/messages, $log_size, /usr/sbin/rotate-messages' >> /etc/rsyslog.conf

```

2024-10-18 14:36 UTC, stephdl commented
Playing with the limit

The value `9223372036854775807` bytes is approximately 8589.93 GB and it is accepted but `9223372036854775808` overflows the  integer limit of bash

2024-10-21 08:28 UTC, gsanchietti approved these changes
Let's wait before merge: I want to release opened issues before adding this new feature.

2024-10-21 12:57 UTC, filippocarletti approved these changes

2024-10-21 14:02 UTC, merged